### ISSUE TITLE
Where should the .rb files be copied to?

### ISSUE THREAD

**Issue by bschonec** [kwilczynski/facter-facts#7]
I'd like to implement some of your facts but I'm unsure as to where they should go.  Is there a way to implement these w/o having to 'facter -p' (for custom facts)?

**Comment by kwilczynski** [comment]
@bschonec sorry for the late reply. For some yet unknown to me reason, github does not send notifications to me as of late.

Check the following:

- https://docs.puppetlabs.com/facter/latest/custom_facts.html
- https://docs.puppetlabs.com/guides/plugins_in_modules.html
- https://groups.google.com/forum/#!topic/puppet-users/irSCu9SVoh4

In short, you should be able to distribute Ruby-based facts (not the same as external facts) using the _pluginsync_ facility. Let me know if you got it to work.

**Comment by kwilczynski** [comment]
@bschonec did you found the answer you were looking for?

**Comment by kwilczynski** [comment]
I am going to close this issue. @bschonec let me know if you need more help.
